name: AnonMC
version: '${version}'
author: Anon
main: eu.caec.anonmc.AnonMC
api-version: '1.20'
description: Carries the idea of anonymous imageboards to Minecraft (except there are no images)
depend:
  - packetevents
commands:
  name:
    description: Changes your name
  moderate:
    description: Moderation tools, only available to operators and jannies
