name: AnonMC
version: '${version}'
author: s4s
main: eu.caec.anonmc.AnonMC
api-version: '1.18'
description: Carries the idea of anonymous imageboards to Minecraft (except there are no images)
depend: [ProtocolLib]
commands:
  name:
    description: Changes your name
  moderate:
    description: Moderation tools, only available to operators and jannies
